### PR TITLE
Add PUBLISH

### PR DESCRIPTION
**Pull request by pranavjain**

### CODE REVIEW

**Comment by dpocock** [comment]
@pranavjain @saghul can you please confirm the PUBLISH support has been tested and then I will accept this pull request and make a new release of MjSIP-fork?

**Comment by saghul** [comment]
It has not been tested yet. We have to wait until the Lumicall bits are ready, because we can't test it standalone.

**Comment by saghul** [comment]
LGTM with style nits: aligned lines, spaces between operators.

**Comment by dpocock** [comment]
@pranavjain @saghul now that we tested PUBLISH, I'd like to get this changed merged ASAP and then release a new JAR that you can depend on.  Can you please confirm if it is finished?  Please make sure the style/formatting is consistent with other methods in the same source file.  MjSIP code formatting doesn't really follow good Java conventions, but we just try to make it look the same as the rest of their code.

**Comment by saghul** [comment]
@dpocock Only the style is missing, the rest is good to merge. @pranavjain can you address the style issues? Please apply them to the function in question, not the entire file. Specifically:
- align { and }
- new line after {
- aligned lines
- spaces between operators

**Comment by pranavjain** [comment]
@dpocock I have updated the styling.

**Comment by saghul** [comment]
Belated LGTM.

**Pull request merged**
